#!/bin/bash
echo "% Autogenerated file, do not edit"
echo "% This file is generated by accumulate.sh"
echo "% To regenerate, run accumulate.sh"
echo "% https://github.com/manasij7479/generalization-examples-llvm-issues"
for i in *.opt; do
    first=`head -n 1 $i`
    second=`head -n 2 $i | tail -n 1`
    third=`head -n 3 $i | tail -n 1`
    # extract all but first two letters
    link=${first:2}
    id=`echo $link | grep -Eo '[0-9]+$'`
    #echo $link $status $id
    #\href{https://github.com/llvm/llvm-project/issues/66733}{66733} & Optimal &          \\
    echo "\href{$link}{$id} & ${second:2} & \$${third:2}\$ \\\\"
done